Repository AnalogStudiosRI/www.tuesdaystunes.tv, pull requests merged in 2022-12, with the labels that each got.

#97 refactor test mocks to only have future events
  src/components/upcoming-events/mock-events.js
  src/components/upcoming-events/upcoming-events.spec.js
Labels: chore

#95 rewrite assets path for storybook github pages builds
  .github/workflows/pages.yml
  .storybook/main.cjs
  package.json
  yarn.lock
Labels: chore

#100 fix missing events from production builds
  src/components/upcoming-events/upcoming-events.js
  src/pages/index.js
Labels: bug

#99 display an indicator besides the next closest upcoming event
  src/components/upcoming-events/mock-events.js
  src/components/upcoming-events/upcoming-events.js
  src/components/upcoming-events/upcoming-events.spec.js
Labels: feature

#103 add lint check for `describe.only` usage in specs
  .eslintrc.cjs
  package.json
  src/components/upcoming-events/upcoming-events.spec.js
  yarn.lock
Labels: chore

#104 fix upcoming events indicator not auto incrementing
  src/components/upcoming-events/upcoming-events.js
  src/components/upcoming-events/upcoming-events.spec.js
Labels: bug

#109 bump ESLint ECMA version support
  .eslintrc.cjs
Labels: chore

#107 Feature/issue 81 contact page
  src/components/nav/nav.js
  src/components/nav/nav.spec.js
  src/pages/contact.html
  src/pages/index.js
  src/templates/app.html
Labels: feature

#112 improve contact form submit button styling
  src/pages/contact.html
Labels: enhancement

#108 Updated Logic for Next Upcoming Event Indicator
  src/components/upcoming-events/mock-events.js
  src/components/upcoming-events/upcoming-events.js
  src/components/upcoming-events/upcoming-events.spec.js
  src/pages/index.js
Labels: bug

#113 minor refactor for testing formatted upcoming events output
  src/components/upcoming-events/upcoming-events.spec.js
Labels: chore
