Repository AnalogStudiosRI/www.tuesdaystunes.tv, pull requests merged in 2022-10, with the labels that each got.

#27 Feature/issue 13 theme and styleguide
  .storybook/main.cjs
  greenwood.config.js
  package.json
  postcss.config.cjs
  postcss.config.mjs
  src/components/footer/footer.js
  src/pages/index.html
  src/stories/Documentation.stories.mdx
  src/stories/Storybook.stories.mdx
  src/stories/Styleguide.stories.mdx
  src/styles/main.css
  src/styles/theme.css
  stylelint.config.cjs
  tailwind.config.cjs
  yarn.lock
Labels: enhancement

#29 additional configuration and styletweaks for Storybook
  .storybook/main.cjs
  src/components/footer/footer.stories.js
  src/styles/main.css
Labels: chore

#35 add tech stack section and clean up styles
  src/stories/Documentation.stories.mdx
  src/stories/Styleguide.stories.mdx
  src/stories/Tech_Stack.stories.mdx
Labels: documentation

#30 Feature/issue 11 footer
  src/assets/icons/facebook.svg
  src/assets/icons/spotify.svg
  src/assets/icons/youtube.svg
  src/components/footer/footer.js
  src/components/footer/footer.spec.js
  src/pages/index.html
Labels: feature

#38 add cooper black font to project
  src/assets/coop_bl.woff2
  src/styles/theme.css
Labels: bug

#39 add standard colors to variables and style guide
  src/assets/icons/facebook.svg
  src/assets/icons/spotify.svg
  src/assets/icons/youtube.svg
  src/components/footer/footer.js
  src/stories/Styleguide.stories.mdx
  src/styles/theme.css
  tailwind.config.cjs
Labels: documentation, enhancement, question, hacktoberfest-accepted

#31 Feature/issue 12 cast and crew
  src/components/cast-and-crew/cast-and-crew.js
  src/components/cast-and-crew/cast-and-crew.spec.js
  src/components/cast-and-crew/cast-and-crew.stories.js
Labels: documentation, feature

#41 add basic header component based on spec
  src/assets/tuesdays-tunes.webp
  src/components/header/header.js
  src/components/header/header.spec.js
  src/components/header/header.stories.js
Labels: documentation, feature, hacktoberfest-accepted

#37 Feature/issue 16 upcoming events
  src/components/upcoming-events/mock-events.js
  src/components/upcoming-events/upcoming-events.js
  src/components/upcoming-events/upcoming-events.spec.js
  src/components/upcoming-events/upcoming-events.stories.js
Labels: documentation, help wanted, feature

#46 sync upcoming events component with API and hack work around for apos…
  src/components/upcoming-events/mock-events.js
  src/components/upcoming-events/upcoming-events.js
  src/components/upcoming-events/upcoming-events.spec.js
  src/components/upcoming-events/upcoming-events.stories.js
Labels: bug, documentation

#42 add favicons and associated files
  src/favicon.ico
  src/pages/index.html
Labels: feature, hacktoberfest-accepted

#43 add Spotify playlist iframe to component
  src/components/spotify_playlist/spotify_playlist.js
  src/components/spotify_playlist/spotify_playlist.spec.js
  src/components/spotify_playlist/spotify_playlist.stories.js
Labels: documentation, feature, hacktoberfest-accepted

#36 feat: :sparkles: YouTube Playlist Component
  src/components/youtube-playlist/youtube-playlist.js
  src/components/youtube-playlist/youtube-playlist.spec.js
  src/components/youtube-playlist/youtube-playlist.stories.js
  yarn.lock
Labels: documentation, feature, hacktoberfest-accepted

#49 Feature/issue 21 home page
  package.json
  src/components/cast-and-crew/cast-and-crew.js
  src/components/spotify-playlist/spotify-playlist.js
  src/components/spotify-playlist/spotify-playlist.spec.js
  src/components/upcoming-events/upcoming-events.js
  src/components/upcoming-events/upcoming-events.spec.js
  src/components/youtube-playlist/youtube-playlist.js
  src/components/youtube-playlist/youtube-playlist.spec.js
  src/pages/index.js
  src/templates/app.html
  yarn.lock
Labels: question, feature

#52 Bug/issue 51 event dates are incorrect prod
  netlify.toml
  src/components/upcoming-events/upcoming-events.js
  src/components/upcoming-events/upcoming-events.spec.js
Labels: bug

#61 apply application side TT events filtering
  src/pages/index.js
Labels: bug

#58 use html entity for hyphen in Tunesy signature
  src/pages/index.js
Labels: enhancement

#59 document integrations and services for the project
  src/stories/Integrations.stories.mdx
Labels: documentation

#64 add .DS_Store to gitignore
  .gitignore
Labels: chore

#65 Feature/issue 44 final design image assets
  src/assets/images/avatar-dave.webp
  src/assets/images/avatar-erika.webp
  src/assets/images/avatar-owen.webp
  src/assets/images/avatar-tunesy.webp
  src/assets/tuesdays-tunes.webp
  src/assets/tunesy.webp
  src/components/cast-and-crew/cast-and-crew.js
  src/components/header/header.js
  src/pages/index.js
Labels: feature

#68 disable the upcoming events links for now
  src/components/upcoming-events/upcoming-events.js
Labels: bug, Integration

#69 revert to old OG image asset to fix social share transparency
  src/assets/tuesdays-tunes-og.webp
  src/templates/app.html
Labels: bug

#70 update home page greeting message
  src/pages/index.js
Labels: enhancement

#72 custom scrollbar effect
  src/styles/main.css
Labels: enhancement, hacktoberfest-accepted

#75 logo fix get behind the content
  src/components/header/header.js
Labels: bug
