Repository AnalogStudiosRI/www.tuesdaystunes.tv, pull requests merged in 2022-11, with the labels that each got.

#80 custom meta og image with background color
  src/assets/tuesdays-tunes-og.png
  src/assets/tuesdays-tunes-og.webp
  src/templates/app.html
Labels: feature

#50 adjust spacing for improved legibility
  src/components/cast-and-crew/cast-and-crew.js
  src/components/header/header.js
  src/pages/index.js
Labels: enhancement, hacktoberfest-accepted

#77 Align upcoming events
  src/components/upcoming-events/upcoming-events.js
Labels: enhancement, hacktoberfest-accepted

#79 Feature/issue 66 enable event linking
  src/components/upcoming-events/mock-events.js
  src/components/upcoming-events/upcoming-events.js
  src/components/upcoming-events/upcoming-events.spec.js
Labels: feature

#93 add GitHub Action for publishing Storybook to GitHub Pages
  .github/workflows/pages.yml
  README.md
Labels: documentation

#92 giving Tunesy logo a little more top padding on non desktop
  README.md
  src/pages/index.js
Labels: enhancement

#90 pre-filter for only TT events from backend
  src/pages/index.js
Labels: enhancement

#76 upgrade Greenwood v0.27.0
  package.json
  yarn.lock
Labels: chore
